config/routes.rb
Rails.application.routes.draw do
  root to:'tasks#index'
  resources :tasks
  resources :labels

  #session routes
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/profil', to:'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  get '/favorites', to: 'posts#favorites', as: :favorites

  #register routes
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  resources :users, only: [:new] do
    member do
      get 'confirm'
    end
  end
  resources :sessions, only: [:new, :destroy]


  #admin
  namespace :admin do
    resources :users
  end
end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :tasks
  belongs_to :user
  validates :name, presence: true
  
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  def index
    @labels = current_user.labels
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(get_params)
    @label.user = current_user
    if @label.save
      redirect_to labels_path
    else
      render 'new', danger: "Error"
    end
  end

  def edit
  end

  def update
    @label.update_attributes(get_params)
    if @labels.save
      redirect_to labels_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @label.destroy
  end

  private
  def set_label
    @label = Label.find(params[:id])
  end

  def get_params
    params.require(:label).permit(:name)
  end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true ) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2 class="h4" ><%= pluralize(label.errors.count, t('view.error') ) %> au cours de l'engeristrement de la tâche</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label :name, class: 'col-sm-2 col-form-label text-start' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= form.submit t('view.create_label') , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<div class="row text-center">
  <h1>Editing Label</h1>

  <%= render 'form', label: @label %>
  <%= link_to 'Show', @label, class: 'text-primary' %> 
  <%= link_to 'Back', labels_path, class: 'text-success' %>
</div>

app/views/labels/index.html.erb
<% if flash[:success].present? || flash[:danger].present? %>
  <div class="alert alert-<%= flash[:success] ? 'success' : 'danger' %>">
    <p id="danger"><%= t(danger) %></p>
    <p id="success"><%= t(success) %></p>
  </div>
<% end %>

<div class="row">
  <div class="col">
    <h1 class="text-center" >Labels</h1>
  </div>
  <div class="col text-end">
    <%= link_to 'New Label', new_label_path, class:'btn btn-primary btn-sm' %>
  </div>
</div>

<table class="table">
  <thead class="table-light">
    <tr class="text-center">
      <th>Name</th>
      <th colspan="3" >Actions</th>
    </tr>
  </thead>

  <tbody>
    
    <% if @labels.empty? %>
      <td colspan="6">
        <h1 class="text-center h2" >No label for a moment. <%= link_to "Create first", new_label_path %> </h1>
      </td>
      
    <% end %>
    
    <% @labels.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task, class: "text-primary" %></td>
        <td><%= link_to 'Edit', edit_label_path(task), class:"text-success" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/labels/new.html.erb
<div class="row text-center">
  <h1>New Label</h1>

  <%= render 'form', label: @label %>
  <%= link_to 'Back', labels_path, class: 'btn btn-link' %>

</div>

app/views/labels/show.html.erb
<p id="danger"><%= t(danger) %></p>
<p id="success"><%= t(success) %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>