config/routes.rb
Rails.application.routes.draw do
  root to:'tasks#index'
  resources :tasks
  resources :labels

  #session routes
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/profil', to:'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  get '/favorites', to: 'posts#favorites', as: :favorites

  #register routes
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  resources :users, only: [:new] do
    member do
      get 'confirm'
    end
  end
  resources :sessions, only: [:new, :destroy]


  #admin
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <span class="fs-4"> <%= Rails.application.config.site[:name] %> </span>
        </a>

        <ul class="nav nav-pills">
        
          <% if logged_in? %>
            <li class="nav-item"><a href=" <%= new_task_path %> " class="nav-link" aria-current="page">Create Task</a></li>
            <li class="nav-item"><a href="<%= tasks_path %>" class="nav-link">My Tasks</a></li>
            <li class="nav-item"><a href="<%= labels_path %>" class="nav-link">My Labels</a></li>
           
            <% if current_user.admin? %>
             <li class="nav-item"><a href=" <%= admin_users_path %> " class="nav-link">Admin</a></li>
            <% end %>
           
            <li class="nav-item"><a href=" <%= profil_path %> " class="nav-link">Profil</a></li>
            <li class="nav-item"><a href=" <%= session_path(current_user.id) %>" data-method="delete" class="nav-link text-danger">Logout</a></li>
          <% else %>
            <li class="nav-item"><a href="<%= register_path %>" class="nav-link">S'inscrire</a></li>
            <li class="nav-item"><a href="<%= login_path %>" class="btn btn-success">Connexion</a></li>
          <% end %>
        
          
        </ul>
      </header>

      <%= yield %>

    </div>
  </body>
</html>